CREATE TABLE IF NOT EXISTS cart (
    Cart_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Product_ID INT NOT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    Date_Added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES user(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Product_ID) REFERENCES product(Product_ID) ON DELETE CASCADE,
    UNIQUE KEY unique_user_product (User_ID, Product_ID)
);

CREATE TABLE IF NOT EXISTS order_items (
    Order_Item_ID INT AUTO_INCREMENT PRIMARY KEY,
    Order_ID INT NOT NULL,
    Product_ID INT NOT NULL,
    Product_Name VARCHAR(255) NOT NULL,
    Product_Price DECIMAL(10,2) NOT NULL,
    Quantity INT NOT NULL,
    Subtotal DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (Order_ID) REFERENCES `order`(Order_ID) ON DELETE CASCADE,
    FOREIGN KEY (Product_ID) REFERENCES product(Product_ID)
);

ALTER TABLE `order` 
ADD COLUMN IF NOT EXISTS Total_Amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS Order_Status VARCHAR(50) DEFAULT 'Pending',
ADD COLUMN IF NOT EXISTS Shipping_Address TEXT,
ADD COLUMN IF NOT EXISTS Payment_Method VARCHAR(50),
ADD COLUMN IF NOT EXISTS Order_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
